"""UI configuration for Eufy Mega Security."""

from __future__ import annotations

from typing import Any

import voluptuous as vol
from homeassistant import config_entries
from homeassistant.config_entries import ConfigFlowResult
from homeassistant.const import CONF_URL
from homeassistant.helpers.aiohttp_client import async_get_clientsession
from homeassistant.helpers.selector import TextSelector, TextSelectorConfig, TextSelectorType
from homeassistant.helpers.service_info.hassio import HassioServiceInfo

from .client import GatewayAuthenticationError, GatewayClient, GatewayClientError
from .const import CONF_API_TOKEN, DOMAIN


class EufyGatewayConfigFlow(config_entries.ConfigFlow, domain=DOMAIN):
    """Configure one local gateway."""

    VERSION = 1
    _discovered_data: dict[str, Any] | None = None

    async def async_step_user(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult:
        """Validate and save the local gateway address."""
        errors: dict[str, str] = {}
        if user_input is not None:
            url = user_input[CONF_URL].rstrip("/")
            client = GatewayClient(
                async_get_clientsession(self.hass), url, user_input.get(CONF_API_TOKEN, "")
            )
            try:
                await client.cameras()
            except GatewayAuthenticationError:
                errors["base"] = "invalid_auth"
            except GatewayClientError:
                errors["base"] = "cannot_connect"
            else:
                await self.async_set_unique_id(url.lower())
                self._abort_if_unique_id_configured()
                return self.async_create_entry(title="Eufy Mega Security", data={**user_input, CONF_URL: url})

        return self.async_show_form(
            step_id="user",
            data_schema=_schema(user_input),
            errors=errors,
        )

    async def async_step_reconfigure(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult:
        """Update the gateway address or API token without removing entities."""
        entry = self._get_reconfigure_entry()
        errors: dict[str, str] = {}
        if user_input is not None:
            url = user_input[CONF_URL].rstrip("/")
            client = GatewayClient(
                async_get_clientsession(self.hass), url, user_input.get(CONF_API_TOKEN, "")
            )
            try:
                await client.cameras()
            except GatewayAuthenticationError:
                errors["base"] = "invalid_auth"
            except GatewayClientError:
                errors["base"] = "cannot_connect"
            else:
                return self.async_update_reload_and_abort(
                    entry,
                    data_updates={**user_input, CONF_URL: url},
                )

        return self.async_show_form(
            step_id="reconfigure",
            data_schema=_schema(user_input or dict(entry.data)),
            errors=errors,
        )

    async def async_step_hassio(self, discovery_info: HassioServiceInfo) -> ConfigFlowResult:
        """Receive private connection details generated by the local app."""
        config = discovery_info.config
        host = config.get("host")
        port = config.get("port")
        api_token = config.get(CONF_API_TOKEN)
        if not isinstance(host, str) or not isinstance(port, int) or not isinstance(api_token, str):
            return self.async_abort(reason="invalid_discovery")

        data = {CONF_URL: f"http://{host}:{port}", CONF_API_TOKEN: api_token}
        client = GatewayClient(async_get_clientsession(self.hass), data[CONF_URL], api_token)
        try:
            await client.cameras()
        except GatewayClientError:
            return self.async_abort(reason="cannot_connect")

        entries = self._async_current_entries(include_ignore=False)
        if entries:
            entry = entries[0]
            self.hass.config_entries.async_update_entry(entry, unique_id=DOMAIN)
            return self.async_update_reload_and_abort(
                entry,
                data_updates=data,
                reason="hassio_connected",
            )

        await self.async_set_unique_id(DOMAIN)
        self._abort_if_unique_id_configured(updates=data)
        self._discovered_data = data
        return await self.async_step_hassio_confirm()

    async def async_step_hassio_confirm(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult:
        """Confirm a newly discovered local app."""
        if user_input is not None:
            assert self._discovered_data is not None
            return self.async_create_entry(title="Eufy Mega Security", data=self._discovered_data)
        return self.async_show_form(step_id="hassio_confirm")


def _schema(defaults: dict[str, Any] | None) -> vol.Schema:
    """Build the connection form with current values when available."""
    values = defaults or {}
    return vol.Schema(
        {
            vol.Required(CONF_URL, default=values.get(CONF_URL, "http://127.0.0.1:3218")): str,
            vol.Optional(CONF_API_TOKEN, default=values.get(CONF_API_TOKEN, "")): TextSelector(
                TextSelectorConfig(type=TextSelectorType.PASSWORD)
            ),
        }
    )
